#!/usr/bin/perl
# Begin [* IF FILE *][* FILE _ '.' _ EXT *][* ELSE *]script[* END *]
######## 
#$# creator : [* AUTHOR *]
#%# email: [* AUTHOR_EMAIL *]
#$# created : [* DATE *]
#$# title : [* IF TITLE; TITLE; ELSE; FILE; END *]
#$# description : 
######## Define a usage function 
sub usage {
	(my $bin = $0) =~ s,^.*/,,;
	print "Usage:\t$bin\n";
	exit if shift eq 'exit';
}
######## Standard use lines
use strict;
use warnings;
#use Log::Log4perl qw(:easy);
#use YAML qw(LoadFile DumpFile Load Dump);
use Template;
#use lib '/some/path';
######## 
#Log::Log4perl->easy_init($DEBUG);
my $config = {
#	INCLUDE_PATH => $TmplDir,
};
######## 

# create Template object
my $tt = Template->new($config);
my $template = \ "";

my $context = { 
html => {
	title => 'HTML Document',
	},
meta => {
	generator => $0,
	generated => scalar localtime,
	},
};

$tt->process($template, $context) || die $tt->error();

######## 
# End [* IF FILE *][* FILE _ '.' _ EXT *][* ELSE *]script[* END *]
# [* VIM *]
